export const SWIGGY_API =
  "https://www.swiggy.com/dapi/restaurants/list/v5?lat=18.5203896&lng=73.8567005";

export const Cors_Key = "temp_d130502ab5f267c34e3d672961bc7d97";

export const RESTO_IMG =
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/";

export const MENU =
  "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=18.4698283&lng=73.87866009999999&restaurantId=";

export const item = [
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Healthy",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "2%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Protein",
    price: "₹40",
    discount: "5%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Green Vegies",
    price: "₹40",
    discount: "10%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Oxycide",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "6%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "9%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
  {
    id: 1,
    qty: "500g",
    name: "Potato",
    tag: "Rich Fiber",
    price: "₹40",
    discount: "20%",
  },
];
